---
title: "02_daymet"
format: html
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(USAboundaries)
library(sf)
library(daymetr)
library(dplyr)
library(readr)
library(readxl)
```

#training 

##Meta
```{r}
meta_train <- read_csv("../data/training/training_meta.csv")

meta_train
```


```{r}
summary(meta_train)
```

unique years
```{r message=FALSE, warning=FALSE}
meta_train %>%
  distinct(year)
```
10 distinct years

unique sites
```{r message=FALSE, warning=FALSE}
meta_train %>%
  distinct(site)
```
43 unique sites


##remove GEH1
```{r}
dw <- meta_train %>%
  filter(site != "GEH1") %>%
  distinct(site,
           year,
    lat = latitude,
    lon = longitude
  )


dw
```
Daymet doesn't cover Germany


```{r}
daymet_train <- dw %>%
  mutate(weather = pmap(list(.y = year,
                             .site = site,
                             .lat = lat,
                             .lon = lon),
                        function(.y, .site, .lat, .lon)
                          download_daymet(
                            site = .site, 
                            lat = .lat,
                            lon = .lon,
                            start = .y,
                            end = .y,
                            simplify = T,
                            silent = T
                          ) %>%
                          rename(.year = year,
                                 .site = site
                                 )
                        ))

daymet_train %>% head()
```


```{r}
daymet_train$weather[1]
```



##export
```{r}
daymet_train_unnest <- daymet_train %>%
  unnest(weather) %>%
  pivot_wider(names_from = measurement,
              values_from = value) %>%
  janitor::clean_names()

daymet_train_unnest
```


Export weather data for training
```{r}
write_csv(daymet_train_unnest, "../data/training/fieldweatherdata_train.csv")
```




#Testing 

##Meta
```{r}
meta_test <- read_csv("../data/testing/testing_meta.csv")

meta_test
```


```{r}
summary(meta_test)
```

unique sites
```{r message=FALSE, warning=FALSE}
meta_test %>%
  distinct(site)
```
23 unique sites


```{r}
dx <- meta_test %>%
  distinct(site,
           year,
    lat = latitude,
    lon = longitude
  )


dx
```


```{r}
daymet_test <- dx %>%
  mutate(weather = pmap(list(.y = year,
                             .site = site,
                             .lat = lat,
                             .lon = lon),
                        function(.y, .site, .lat, .lon)
                          download_daymet(
                            site = .site, 
                            lat = .lat,
                            lon = .lon,
                            start = .y,
                            end = .y,
                            simplify = T,
                            silent = T
                          ) %>%
                          rename(.year = year,
                                 .site = site
                                 )
                        ))

daymet_test %>% head()
```


```{r}
daymet_test$weather[1]
```


```{r}
daymet_test_unnest <- daymet_test %>%
  unnest(weather) %>%
  pivot_wider(names_from = measurement,
              values_from = value) %>%
  janitor::clean_names()

daymet_test_unnest

```


##export
```{r}
write_csv(daymet_test_unnest, "../data/testing/fieldweatherdata_test.csv")
```


